"""empty message

Revision ID: 8bea15b458bc
Revises: e86bbd164096
Create Date: 2020-03-14 11:37:50.494227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bea15b458bc'
down_revision = 'e86bbd164096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
